1, 
圣淘沙岛
  
, page: None, 2020-01-31 17:03:28.039469
Traceback (most recent call last):
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 157, in crawl_pois
    self.crawl_reviews()
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 297, in crawl_reviews
    self.crawl_reviews_1_page(self.current_poi_index)
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 387, in crawl_reviews_1_page
    raise Exception("random clicking happened")
Exception: random clicking happened

1, 
圣淘沙岛
  
, page: None, 2020-01-31 17:03:43.736943
Traceback (most recent call last):
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 157, in crawl_pois
    self.crawl_reviews()
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 297, in crawl_reviews
    self.crawl_reviews_1_page(self.current_poi_index)
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 387, in crawl_reviews_1_page
    raise Exception("random clicking happened")
Exception: random clicking happened

6, 
克拉码头
  
, page: None, 2020-01-31 17:05:10.579689
Traceback (most recent call last):
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 157, in crawl_pois
    self.crawl_reviews()
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 297, in crawl_reviews
    self.crawl_reviews_1_page(self.current_poi_index)
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 379, in crawl_reviews_1_page
    raise Exception("wrong_page")
Exception: wrong_page

6, 
克拉码头
  
, page: None, 2020-01-31 17:05:29.706973
Traceback (most recent call last):
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 157, in crawl_pois
    self.crawl_reviews()
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 297, in crawl_reviews
    self.crawl_reviews_1_page(self.current_poi_index)
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 387, in crawl_reviews_1_page
    raise Exception("random clicking happened")
Exception: random clicking happened

