Error in API call.
POI index: 45, review ID: 735525393, row index: 0, time: 2020-02-10 11:26:45.822534
Traceback (most recent call last):
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 185, in score_sentiments_1_poi
    self.get_api_response()
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 245, in get_api_response
    keywords=KeywordsOptions(emotion=True, sentiment=True, limit=10000)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_watson/natural_language_understanding_v1.py", line 186, in analyze
    response = self.send(request)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_cloud_sdk_core/base_service.py", line 157, in send
    response.status_code, error_message, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: Error: Forbidden, Code: 403

API key 0 has been exhausted.
Error in API call.
POI index: 45, review ID: 735525393, row index: 0, time: 2020-02-10 11:26:47.930006
Traceback (most recent call last):
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 185, in score_sentiments_1_poi
    self.get_api_response()
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 245, in get_api_response
    keywords=KeywordsOptions(emotion=True, sentiment=True, limit=10000)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_watson/natural_language_understanding_v1.py", line 186, in analyze
    response = self.send(request)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_cloud_sdk_core/base_service.py", line 157, in send
    response.status_code, error_message, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: Error: Forbidden, Code: 403

API key 1 has been exhausted.
Error in API call.
POI index: 45, review ID: 735525393, row index: 0, time: 2020-02-10 11:26:49.191604
Traceback (most recent call last):
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 185, in score_sentiments_1_poi
    self.get_api_response()
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 245, in get_api_response
    keywords=KeywordsOptions(emotion=True, sentiment=True, limit=10000)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_watson/natural_language_understanding_v1.py", line 186, in analyze
    response = self.send(request)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_cloud_sdk_core/base_service.py", line 157, in send
    response.status_code, error_message, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: Error: Forbidden, Code: 403

API key 2 has been exhausted.
