Error in API call.
POI index: 13, review ID: 741799483, row index: 0, time: 2020-02-09 13:57:27.607668
Traceback (most recent call last):
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 179, in score_sentiments_1_poi
    self.get_api_response()
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 239, in get_api_response
    keywords=KeywordsOptions(emotion=True, sentiment=True, limit=10000)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_watson/natural_language_understanding_v1.py", line 186, in analyze
    response = self.send(request)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_cloud_sdk_core/base_service.py", line 157, in send
    response.status_code, error_message, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: Error: Forbidden, Code: 403

API key 0 has been exhausted.
Error in API call.
POI index: 13, review ID: 741799483, row index: 0, time: 2020-02-09 13:57:33.849985
Traceback (most recent call last):
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 179, in score_sentiments_1_poi
    self.get_api_response()
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 239, in get_api_response
    keywords=KeywordsOptions(emotion=True, sentiment=True, limit=10000)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_watson/natural_language_understanding_v1.py", line 186, in analyze
    response = self.send(request)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_cloud_sdk_core/base_service.py", line 157, in send
    response.status_code, error_message, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: Error: Forbidden, Code: 403

API key 1 has been exhausted.
Error in API call.
POI index: 13, review ID: 741799483, row index: 0, time: 2020-02-09 13:57:40.301152
Traceback (most recent call last):
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 179, in score_sentiments_1_poi
    self.get_api_response()
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 239, in get_api_response
    keywords=KeywordsOptions(emotion=True, sentiment=True, limit=10000)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_watson/natural_language_understanding_v1.py", line 186, in analyze
    response = self.send(request)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_cloud_sdk_core/base_service.py", line 157, in send
    response.status_code, error_message, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: Error: Forbidden, Code: 403

API key 2 has been exhausted.
Error in API call.
POI index: 13, review ID: 373322610, row index: 1115, time: 2020-02-09 14:14:50.017508
Traceback (most recent call last):
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 179, in score_sentiments_1_poi
    self.get_api_response()
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 239, in get_api_response
    keywords=KeywordsOptions(emotion=True, sentiment=True, limit=10000)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_watson/natural_language_understanding_v1.py", line 186, in analyze
    response = self.send(request)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_cloud_sdk_core/base_service.py", line 157, in send
    response.status_code, error_message, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: Error: unsupported text language: th, Code: 400 , X-global-transaction-id: a9d5a3948698eccdbd331fdd6b803902

Error in API call.
POI index: 13, review ID: 619306953, row index: 4101, time: 2020-02-09 15:23:08.982409
Traceback (most recent call last):
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 179, in score_sentiments_1_poi
    self.get_api_response()
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 239, in get_api_response
    keywords=KeywordsOptions(emotion=True, sentiment=True, limit=10000)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_watson/natural_language_understanding_v1.py", line 186, in analyze
    response = self.send(request)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_cloud_sdk_core/base_service.py", line 157, in send
    response.status_code, error_message, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: Error: <HTML><HEAD>
<TITLE>Internal Server Error</TITLE>
</HEAD><BODY>
<H1>Internal Server Error - Read</H1>
The server encountered an internal error or misconfiguration and was unable to
complete your request.<P>
Reference&#32;&#35;3&#46;dd861402&#46;1581232988&#46;11f08111
</BODY></HTML>
, Code: 500

Error in API call.
POI index: 13, review ID: 618039140, row index: 4104, time: 2020-02-09 15:23:38.447403
Traceback (most recent call last):
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 179, in score_sentiments_1_poi
    self.get_api_response()
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 239, in get_api_response
    keywords=KeywordsOptions(emotion=True, sentiment=True, limit=10000)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_watson/natural_language_understanding_v1.py", line 186, in analyze
    response = self.send(request)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_cloud_sdk_core/base_service.py", line 157, in send
    response.status_code, error_message, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: Error: <HTML><HEAD>
<TITLE>Internal Server Error</TITLE>
</HEAD><BODY>
<H1>Internal Server Error - Read</H1>
The server encountered an internal error or misconfiguration and was unable to
complete your request.<P>
Reference&#32;&#35;3&#46;dd861402&#46;1581233018&#46;11f11e35
</BODY></HTML>
, Code: 500

